#!/bin/bash
# Install albert using an install script
# Fetch the source from the upstream repo and download it on the user machine
set -euo pipefail
IFS=$'\n\t'

# Change to temporary directory
cd $(mktemp -d)

echo 'Installing build dependencies...'
echo 'Adding upstream source to local sources...'
echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list

echo 'Adding upstream gpg key to local keyring for trust...'
curl -fsSL https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_manuelschneid3r.gpg > /dev/null

echo 'Updating sources...' 
sudo apt update

echo 'Run the command sudo apt install albert to install the Albert application launcher'
